"""add_host_disk_records

Revision ID: f85a3d682562
Revises: 68ea7ce5bae9
Create Date: 2026-06-10 07:31:03.134236+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f85a3d682562'
down_revision: Union[str, None] = '68ea7ce5bae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host_disk_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('mountpoint', sa.String(), nullable=False),
    sa.Column('device', sa.String(), nullable=False),
    sa.Column('fstype', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('used_bytes', sa.BigInteger(), nullable=False),
    sa.Column('avail_bytes', sa.BigInteger(), nullable=False),
    sa.Column('use_pct', sa.Float(), nullable=False),
    sa.Column('inodes_total', sa.BigInteger(), nullable=True),
    sa.Column('inodes_used', sa.BigInteger(), nullable=True),
    sa.Column('inode_use_pct', sa.Float(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'mountpoint', name='uq_host_disk_host_mountpoint')
    )
    op.create_index(op.f('ix_host_disk_records_host_id'), 'host_disk_records', ['host_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_host_disk_records_host_id'), table_name='host_disk_records')
    op.drop_table('host_disk_records')
    # ### end Alembic commands ###
